# Site settings
title: Applied Data Analysis using SparkR
email: daniel.emaasit@gmail.com
description: This is the an on-line book titled "Applied Data Analysis using SparkR". The book is designed primarly for R users who want to learn SparkR
baseurl: "/applied-sparkR" # the subpath of your site, e.g. /blog/
url: "http://danielemaasit.com" # the base hostname & protocol for your site
twitter_username: emaasit
github_username:  emaasit

# Build settings
markdown: kramdown
highlighter: pygments
